// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SupplierDueDiligence.API.Data;

#nullable disable

namespace SupplierDueDiligence.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250605001955_AddScreeningSources")]
    partial class AddScreeningSources
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SupplierDueDiligence.API.Domain.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Iso")
                        .IsRequired()
                        .HasColumnType("char(2)")
                        .IsFixedLength();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Iso = "AF",
                            Name = "Afganistán"
                        },
                        new
                        {
                            Id = 2,
                            Iso = "AX",
                            Name = "Islas Gland"
                        },
                        new
                        {
                            Id = 3,
                            Iso = "AL",
                            Name = "Albania"
                        },
                        new
                        {
                            Id = 4,
                            Iso = "DE",
                            Name = "Alemania"
                        },
                        new
                        {
                            Id = 5,
                            Iso = "AD",
                            Name = "Andorra"
                        },
                        new
                        {
                            Id = 6,
                            Iso = "AO",
                            Name = "Angola"
                        },
                        new
                        {
                            Id = 7,
                            Iso = "AI",
                            Name = "Anguilla"
                        },
                        new
                        {
                            Id = 8,
                            Iso = "AQ",
                            Name = "Antártida"
                        },
                        new
                        {
                            Id = 9,
                            Iso = "AG",
                            Name = "Antigua y Barbuda"
                        },
                        new
                        {
                            Id = 10,
                            Iso = "AN",
                            Name = "Antillas Holandesas"
                        },
                        new
                        {
                            Id = 11,
                            Iso = "SA",
                            Name = "Arabia Saudí"
                        },
                        new
                        {
                            Id = 12,
                            Iso = "DZ",
                            Name = "Argelia"
                        },
                        new
                        {
                            Id = 13,
                            Iso = "AR",
                            Name = "Argentina"
                        },
                        new
                        {
                            Id = 14,
                            Iso = "AM",
                            Name = "Armenia"
                        },
                        new
                        {
                            Id = 15,
                            Iso = "AW",
                            Name = "Aruba"
                        },
                        new
                        {
                            Id = 16,
                            Iso = "AU",
                            Name = "Australia"
                        },
                        new
                        {
                            Id = 17,
                            Iso = "AT",
                            Name = "Austria"
                        },
                        new
                        {
                            Id = 18,
                            Iso = "AZ",
                            Name = "Azerbaiyán"
                        },
                        new
                        {
                            Id = 19,
                            Iso = "BS",
                            Name = "Bahamas"
                        },
                        new
                        {
                            Id = 20,
                            Iso = "BH",
                            Name = "Bahréin"
                        },
                        new
                        {
                            Id = 21,
                            Iso = "BD",
                            Name = "Bangladesh"
                        },
                        new
                        {
                            Id = 22,
                            Iso = "BB",
                            Name = "Barbados"
                        },
                        new
                        {
                            Id = 23,
                            Iso = "BY",
                            Name = "Bielorrusia"
                        },
                        new
                        {
                            Id = 24,
                            Iso = "BE",
                            Name = "Bélgica"
                        },
                        new
                        {
                            Id = 25,
                            Iso = "BZ",
                            Name = "Belice"
                        },
                        new
                        {
                            Id = 26,
                            Iso = "BJ",
                            Name = "Benin"
                        },
                        new
                        {
                            Id = 27,
                            Iso = "BM",
                            Name = "Bermudas"
                        },
                        new
                        {
                            Id = 28,
                            Iso = "BT",
                            Name = "Bhután"
                        },
                        new
                        {
                            Id = 29,
                            Iso = "BO",
                            Name = "Bolivia"
                        },
                        new
                        {
                            Id = 30,
                            Iso = "BA",
                            Name = "Bosnia y Herzegovina"
                        },
                        new
                        {
                            Id = 31,
                            Iso = "BW",
                            Name = "Botsuana"
                        },
                        new
                        {
                            Id = 32,
                            Iso = "BV",
                            Name = "Isla Bouvet"
                        },
                        new
                        {
                            Id = 33,
                            Iso = "BR",
                            Name = "Brasil"
                        },
                        new
                        {
                            Id = 34,
                            Iso = "BN",
                            Name = "Brunéi"
                        },
                        new
                        {
                            Id = 35,
                            Iso = "BG",
                            Name = "Bulgaria"
                        },
                        new
                        {
                            Id = 36,
                            Iso = "BF",
                            Name = "Burkina Faso"
                        },
                        new
                        {
                            Id = 37,
                            Iso = "BI",
                            Name = "Burundi"
                        },
                        new
                        {
                            Id = 38,
                            Iso = "CV",
                            Name = "Cabo Verde"
                        },
                        new
                        {
                            Id = 39,
                            Iso = "KY",
                            Name = "Islas Caimán"
                        },
                        new
                        {
                            Id = 40,
                            Iso = "KH",
                            Name = "Camboya"
                        },
                        new
                        {
                            Id = 41,
                            Iso = "CM",
                            Name = "Camerún"
                        },
                        new
                        {
                            Id = 42,
                            Iso = "CA",
                            Name = "Canadá"
                        },
                        new
                        {
                            Id = 43,
                            Iso = "CF",
                            Name = "República Centroafricana"
                        },
                        new
                        {
                            Id = 44,
                            Iso = "TD",
                            Name = "Chad"
                        },
                        new
                        {
                            Id = 45,
                            Iso = "CZ",
                            Name = "República Checa"
                        },
                        new
                        {
                            Id = 46,
                            Iso = "CL",
                            Name = "Chile"
                        },
                        new
                        {
                            Id = 47,
                            Iso = "CN",
                            Name = "China"
                        },
                        new
                        {
                            Id = 48,
                            Iso = "CY",
                            Name = "Chipre"
                        },
                        new
                        {
                            Id = 49,
                            Iso = "CX",
                            Name = "Isla de Navidad"
                        },
                        new
                        {
                            Id = 50,
                            Iso = "VA",
                            Name = "Ciudad del Vaticano"
                        },
                        new
                        {
                            Id = 51,
                            Iso = "CC",
                            Name = "Islas Cocos"
                        },
                        new
                        {
                            Id = 52,
                            Iso = "CO",
                            Name = "Colombia"
                        },
                        new
                        {
                            Id = 53,
                            Iso = "KM",
                            Name = "Comoras"
                        },
                        new
                        {
                            Id = 54,
                            Iso = "CD",
                            Name = "República Democrática del Congo"
                        },
                        new
                        {
                            Id = 55,
                            Iso = "CG",
                            Name = "Congo"
                        },
                        new
                        {
                            Id = 56,
                            Iso = "CK",
                            Name = "Islas Cook"
                        },
                        new
                        {
                            Id = 57,
                            Iso = "KP",
                            Name = "Corea del Norte"
                        },
                        new
                        {
                            Id = 58,
                            Iso = "KR",
                            Name = "Corea del Sur"
                        },
                        new
                        {
                            Id = 59,
                            Iso = "CI",
                            Name = "Costa de Marfil"
                        },
                        new
                        {
                            Id = 60,
                            Iso = "CR",
                            Name = "Costa Rica"
                        },
                        new
                        {
                            Id = 61,
                            Iso = "HR",
                            Name = "Croacia"
                        },
                        new
                        {
                            Id = 62,
                            Iso = "CU",
                            Name = "Cuba"
                        },
                        new
                        {
                            Id = 63,
                            Iso = "DK",
                            Name = "Dinamarca"
                        },
                        new
                        {
                            Id = 64,
                            Iso = "DM",
                            Name = "Dominica"
                        },
                        new
                        {
                            Id = 65,
                            Iso = "DO",
                            Name = "República Dominicana"
                        },
                        new
                        {
                            Id = 66,
                            Iso = "EC",
                            Name = "Ecuador"
                        },
                        new
                        {
                            Id = 67,
                            Iso = "EG",
                            Name = "Egipto"
                        },
                        new
                        {
                            Id = 68,
                            Iso = "SV",
                            Name = "El Salvador"
                        },
                        new
                        {
                            Id = 69,
                            Iso = "AE",
                            Name = "Emiratos Árabes Unidos"
                        },
                        new
                        {
                            Id = 70,
                            Iso = "ER",
                            Name = "Eritrea"
                        },
                        new
                        {
                            Id = 71,
                            Iso = "SK",
                            Name = "Eslovaquia"
                        },
                        new
                        {
                            Id = 72,
                            Iso = "SI",
                            Name = "Eslovenia"
                        },
                        new
                        {
                            Id = 73,
                            Iso = "ES",
                            Name = "España"
                        },
                        new
                        {
                            Id = 74,
                            Iso = "UM",
                            Name = "Islas ultramarinas de Estados Unidos"
                        },
                        new
                        {
                            Id = 75,
                            Iso = "US",
                            Name = "Estados Unidos"
                        },
                        new
                        {
                            Id = 76,
                            Iso = "EE",
                            Name = "Estonia"
                        },
                        new
                        {
                            Id = 77,
                            Iso = "ET",
                            Name = "Etiopía"
                        },
                        new
                        {
                            Id = 78,
                            Iso = "FO",
                            Name = "Islas Feroe"
                        },
                        new
                        {
                            Id = 79,
                            Iso = "PH",
                            Name = "Filipinas"
                        },
                        new
                        {
                            Id = 80,
                            Iso = "FI",
                            Name = "Finlandia"
                        },
                        new
                        {
                            Id = 81,
                            Iso = "FJ",
                            Name = "Fiyi"
                        },
                        new
                        {
                            Id = 82,
                            Iso = "FR",
                            Name = "Francia"
                        },
                        new
                        {
                            Id = 83,
                            Iso = "GA",
                            Name = "Gabón"
                        },
                        new
                        {
                            Id = 84,
                            Iso = "GM",
                            Name = "Gambia"
                        },
                        new
                        {
                            Id = 85,
                            Iso = "GE",
                            Name = "Georgia"
                        },
                        new
                        {
                            Id = 86,
                            Iso = "GS",
                            Name = "Islas Georgias del Sur y Sandwich del Sur"
                        },
                        new
                        {
                            Id = 87,
                            Iso = "GH",
                            Name = "Ghana"
                        },
                        new
                        {
                            Id = 88,
                            Iso = "GI",
                            Name = "Gibraltar"
                        },
                        new
                        {
                            Id = 89,
                            Iso = "GD",
                            Name = "Granada"
                        },
                        new
                        {
                            Id = 90,
                            Iso = "GR",
                            Name = "Grecia"
                        },
                        new
                        {
                            Id = 91,
                            Iso = "GL",
                            Name = "Groenlandia"
                        },
                        new
                        {
                            Id = 92,
                            Iso = "GP",
                            Name = "Guadalupe"
                        },
                        new
                        {
                            Id = 93,
                            Iso = "GU",
                            Name = "Guam"
                        },
                        new
                        {
                            Id = 94,
                            Iso = "GT",
                            Name = "Guatemala"
                        },
                        new
                        {
                            Id = 95,
                            Iso = "GF",
                            Name = "Guayana Francesa"
                        },
                        new
                        {
                            Id = 96,
                            Iso = "GN",
                            Name = "Guinea"
                        },
                        new
                        {
                            Id = 97,
                            Iso = "GQ",
                            Name = "Guinea Ecuatorial"
                        },
                        new
                        {
                            Id = 98,
                            Iso = "GW",
                            Name = "Guinea-Bissau"
                        },
                        new
                        {
                            Id = 99,
                            Iso = "GY",
                            Name = "Guyana"
                        },
                        new
                        {
                            Id = 100,
                            Iso = "HT",
                            Name = "Haití"
                        },
                        new
                        {
                            Id = 101,
                            Iso = "HM",
                            Name = "Islas Heard y McDonald"
                        },
                        new
                        {
                            Id = 102,
                            Iso = "HN",
                            Name = "Honduras"
                        },
                        new
                        {
                            Id = 103,
                            Iso = "HK",
                            Name = "Hong Kong"
                        },
                        new
                        {
                            Id = 104,
                            Iso = "HU",
                            Name = "Hungría"
                        },
                        new
                        {
                            Id = 105,
                            Iso = "IN",
                            Name = "India"
                        },
                        new
                        {
                            Id = 106,
                            Iso = "ID",
                            Name = "Indonesia"
                        },
                        new
                        {
                            Id = 107,
                            Iso = "IR",
                            Name = "Irán"
                        },
                        new
                        {
                            Id = 108,
                            Iso = "IQ",
                            Name = "Iraq"
                        },
                        new
                        {
                            Id = 109,
                            Iso = "IE",
                            Name = "Irlanda"
                        },
                        new
                        {
                            Id = 110,
                            Iso = "IS",
                            Name = "Islandia"
                        },
                        new
                        {
                            Id = 111,
                            Iso = "IL",
                            Name = "Israel"
                        },
                        new
                        {
                            Id = 112,
                            Iso = "IT",
                            Name = "Italia"
                        },
                        new
                        {
                            Id = 113,
                            Iso = "JM",
                            Name = "Jamaica"
                        },
                        new
                        {
                            Id = 114,
                            Iso = "JP",
                            Name = "Japón"
                        },
                        new
                        {
                            Id = 115,
                            Iso = "JO",
                            Name = "Jordania"
                        },
                        new
                        {
                            Id = 116,
                            Iso = "KZ",
                            Name = "Kazajstán"
                        },
                        new
                        {
                            Id = 117,
                            Iso = "KE",
                            Name = "Kenia"
                        },
                        new
                        {
                            Id = 118,
                            Iso = "KG",
                            Name = "Kirguistán"
                        },
                        new
                        {
                            Id = 119,
                            Iso = "KI",
                            Name = "Kiribati"
                        },
                        new
                        {
                            Id = 120,
                            Iso = "KW",
                            Name = "Kuwait"
                        },
                        new
                        {
                            Id = 121,
                            Iso = "LA",
                            Name = "Laos"
                        },
                        new
                        {
                            Id = 122,
                            Iso = "LS",
                            Name = "Lesotho"
                        },
                        new
                        {
                            Id = 123,
                            Iso = "LV",
                            Name = "Letonia"
                        },
                        new
                        {
                            Id = 124,
                            Iso = "LB",
                            Name = "Líbano"
                        },
                        new
                        {
                            Id = 125,
                            Iso = "LR",
                            Name = "Liberia"
                        },
                        new
                        {
                            Id = 126,
                            Iso = "LY",
                            Name = "Libia"
                        },
                        new
                        {
                            Id = 127,
                            Iso = "LI",
                            Name = "Liechtenstein"
                        },
                        new
                        {
                            Id = 128,
                            Iso = "LT",
                            Name = "Lituania"
                        },
                        new
                        {
                            Id = 129,
                            Iso = "LU",
                            Name = "Luxemburgo"
                        },
                        new
                        {
                            Id = 130,
                            Iso = "MO",
                            Name = "Macao"
                        },
                        new
                        {
                            Id = 131,
                            Iso = "MK",
                            Name = "ARY Macedonia"
                        },
                        new
                        {
                            Id = 132,
                            Iso = "MG",
                            Name = "Madagascar"
                        },
                        new
                        {
                            Id = 133,
                            Iso = "MY",
                            Name = "Malasia"
                        },
                        new
                        {
                            Id = 134,
                            Iso = "MW",
                            Name = "Malawi"
                        },
                        new
                        {
                            Id = 135,
                            Iso = "MV",
                            Name = "Maldivas"
                        },
                        new
                        {
                            Id = 136,
                            Iso = "ML",
                            Name = "Malí"
                        },
                        new
                        {
                            Id = 137,
                            Iso = "MT",
                            Name = "Malta"
                        },
                        new
                        {
                            Id = 138,
                            Iso = "FK",
                            Name = "Islas Malvinas"
                        },
                        new
                        {
                            Id = 139,
                            Iso = "MP",
                            Name = "Islas Marianas del Norte"
                        },
                        new
                        {
                            Id = 140,
                            Iso = "MA",
                            Name = "Marruecos"
                        },
                        new
                        {
                            Id = 141,
                            Iso = "MH",
                            Name = "Islas Marshall"
                        },
                        new
                        {
                            Id = 142,
                            Iso = "MQ",
                            Name = "Martinica"
                        },
                        new
                        {
                            Id = 143,
                            Iso = "MU",
                            Name = "Mauricio"
                        },
                        new
                        {
                            Id = 144,
                            Iso = "MR",
                            Name = "Mauritania"
                        },
                        new
                        {
                            Id = 145,
                            Iso = "YT",
                            Name = "Mayotte"
                        },
                        new
                        {
                            Id = 146,
                            Iso = "MX",
                            Name = "México"
                        },
                        new
                        {
                            Id = 147,
                            Iso = "FM",
                            Name = "Micronesia"
                        },
                        new
                        {
                            Id = 148,
                            Iso = "MD",
                            Name = "Moldavia"
                        },
                        new
                        {
                            Id = 149,
                            Iso = "MC",
                            Name = "Mónaco"
                        },
                        new
                        {
                            Id = 150,
                            Iso = "MN",
                            Name = "Mongolia"
                        },
                        new
                        {
                            Id = 151,
                            Iso = "MS",
                            Name = "Montserrat"
                        },
                        new
                        {
                            Id = 152,
                            Iso = "MZ",
                            Name = "Mozambique"
                        },
                        new
                        {
                            Id = 153,
                            Iso = "MM",
                            Name = "Myanmar"
                        },
                        new
                        {
                            Id = 154,
                            Iso = "NA",
                            Name = "Namibia"
                        },
                        new
                        {
                            Id = 155,
                            Iso = "NR",
                            Name = "Nauru"
                        },
                        new
                        {
                            Id = 156,
                            Iso = "NP",
                            Name = "Nepal"
                        },
                        new
                        {
                            Id = 157,
                            Iso = "NI",
                            Name = "Nicaragua"
                        },
                        new
                        {
                            Id = 158,
                            Iso = "NE",
                            Name = "Níger"
                        },
                        new
                        {
                            Id = 159,
                            Iso = "NG",
                            Name = "Nigeria"
                        },
                        new
                        {
                            Id = 160,
                            Iso = "NU",
                            Name = "Niue"
                        },
                        new
                        {
                            Id = 161,
                            Iso = "NF",
                            Name = "Isla Norfolk"
                        },
                        new
                        {
                            Id = 162,
                            Iso = "NO",
                            Name = "Noruega"
                        },
                        new
                        {
                            Id = 163,
                            Iso = "NC",
                            Name = "Nueva Caledonia"
                        },
                        new
                        {
                            Id = 164,
                            Iso = "NZ",
                            Name = "Nueva Zelanda"
                        },
                        new
                        {
                            Id = 165,
                            Iso = "OM",
                            Name = "Omán"
                        },
                        new
                        {
                            Id = 166,
                            Iso = "NL",
                            Name = "Países Bajos"
                        },
                        new
                        {
                            Id = 167,
                            Iso = "PK",
                            Name = "Pakistán"
                        },
                        new
                        {
                            Id = 168,
                            Iso = "PW",
                            Name = "Palau"
                        },
                        new
                        {
                            Id = 169,
                            Iso = "PS",
                            Name = "Palestina"
                        },
                        new
                        {
                            Id = 170,
                            Iso = "PA",
                            Name = "Panamá"
                        },
                        new
                        {
                            Id = 171,
                            Iso = "PG",
                            Name = "Papúa Nueva Guinea"
                        },
                        new
                        {
                            Id = 172,
                            Iso = "PY",
                            Name = "Paraguay"
                        },
                        new
                        {
                            Id = 173,
                            Iso = "PE",
                            Name = "Perú"
                        },
                        new
                        {
                            Id = 174,
                            Iso = "PN",
                            Name = "Islas Pitcairn"
                        },
                        new
                        {
                            Id = 175,
                            Iso = "PF",
                            Name = "Polinesia Francesa"
                        },
                        new
                        {
                            Id = 176,
                            Iso = "PL",
                            Name = "Polonia"
                        },
                        new
                        {
                            Id = 177,
                            Iso = "PT",
                            Name = "Portugal"
                        },
                        new
                        {
                            Id = 178,
                            Iso = "PR",
                            Name = "Puerto Rico"
                        },
                        new
                        {
                            Id = 179,
                            Iso = "QA",
                            Name = "Qatar"
                        },
                        new
                        {
                            Id = 180,
                            Iso = "GB",
                            Name = "Reino Unido"
                        },
                        new
                        {
                            Id = 181,
                            Iso = "RE",
                            Name = "Reunión"
                        },
                        new
                        {
                            Id = 182,
                            Iso = "RW",
                            Name = "Ruanda"
                        },
                        new
                        {
                            Id = 183,
                            Iso = "RO",
                            Name = "Rumania"
                        },
                        new
                        {
                            Id = 184,
                            Iso = "RU",
                            Name = "Rusia"
                        },
                        new
                        {
                            Id = 185,
                            Iso = "EH",
                            Name = "Sahara Occidental"
                        },
                        new
                        {
                            Id = 186,
                            Iso = "SB",
                            Name = "Islas Salomón"
                        },
                        new
                        {
                            Id = 187,
                            Iso = "WS",
                            Name = "Samoa"
                        },
                        new
                        {
                            Id = 188,
                            Iso = "AS",
                            Name = "Samoa Americana"
                        },
                        new
                        {
                            Id = 189,
                            Iso = "KN",
                            Name = "San Cristóbal y Nevis"
                        },
                        new
                        {
                            Id = 190,
                            Iso = "SM",
                            Name = "San Marino"
                        },
                        new
                        {
                            Id = 191,
                            Iso = "PM",
                            Name = "San Pedro y Miquelón"
                        },
                        new
                        {
                            Id = 192,
                            Iso = "VC",
                            Name = "San Vicente y las Granadinas"
                        },
                        new
                        {
                            Id = 193,
                            Iso = "SH",
                            Name = "Santa Helena"
                        },
                        new
                        {
                            Id = 194,
                            Iso = "LC",
                            Name = "Santa Lucía"
                        },
                        new
                        {
                            Id = 195,
                            Iso = "ST",
                            Name = "Santo Tomé y Príncipe"
                        },
                        new
                        {
                            Id = 196,
                            Iso = "SN",
                            Name = "Senegal"
                        },
                        new
                        {
                            Id = 197,
                            Iso = "CS",
                            Name = "Serbia y Montenegro"
                        },
                        new
                        {
                            Id = 198,
                            Iso = "SC",
                            Name = "Seychelles"
                        },
                        new
                        {
                            Id = 199,
                            Iso = "SL",
                            Name = "Sierra Leona"
                        },
                        new
                        {
                            Id = 200,
                            Iso = "SG",
                            Name = "Singapur"
                        },
                        new
                        {
                            Id = 201,
                            Iso = "SY",
                            Name = "Siria"
                        },
                        new
                        {
                            Id = 202,
                            Iso = "SO",
                            Name = "Somalia"
                        },
                        new
                        {
                            Id = 203,
                            Iso = "LK",
                            Name = "Sri Lanka"
                        },
                        new
                        {
                            Id = 204,
                            Iso = "SZ",
                            Name = "Suazilandia"
                        },
                        new
                        {
                            Id = 205,
                            Iso = "ZA",
                            Name = "Sudáfrica"
                        },
                        new
                        {
                            Id = 206,
                            Iso = "SD",
                            Name = "Sudán"
                        },
                        new
                        {
                            Id = 207,
                            Iso = "SE",
                            Name = "Suecia"
                        },
                        new
                        {
                            Id = 208,
                            Iso = "CH",
                            Name = "Suiza"
                        },
                        new
                        {
                            Id = 209,
                            Iso = "SR",
                            Name = "Surinam"
                        },
                        new
                        {
                            Id = 210,
                            Iso = "SJ",
                            Name = "Svalbard y Jan Mayen"
                        },
                        new
                        {
                            Id = 211,
                            Iso = "TH",
                            Name = "Tailandia"
                        },
                        new
                        {
                            Id = 212,
                            Iso = "TW",
                            Name = "Taiwán"
                        },
                        new
                        {
                            Id = 213,
                            Iso = "TZ",
                            Name = "Tanzania"
                        },
                        new
                        {
                            Id = 214,
                            Iso = "TJ",
                            Name = "Tayikistán"
                        },
                        new
                        {
                            Id = 215,
                            Iso = "IO",
                            Name = "Territorio Británico del Océano Índico"
                        },
                        new
                        {
                            Id = 216,
                            Iso = "TF",
                            Name = "Territorios Australes Franceses"
                        },
                        new
                        {
                            Id = 217,
                            Iso = "TL",
                            Name = "Timor Oriental"
                        },
                        new
                        {
                            Id = 218,
                            Iso = "TG",
                            Name = "Togo"
                        },
                        new
                        {
                            Id = 219,
                            Iso = "TK",
                            Name = "Tokelau"
                        },
                        new
                        {
                            Id = 220,
                            Iso = "TO",
                            Name = "Tonga"
                        },
                        new
                        {
                            Id = 221,
                            Iso = "TT",
                            Name = "Trinidad y Tobago"
                        },
                        new
                        {
                            Id = 222,
                            Iso = "TN",
                            Name = "Túnez"
                        },
                        new
                        {
                            Id = 223,
                            Iso = "TC",
                            Name = "Islas Turcas y Caicos"
                        },
                        new
                        {
                            Id = 224,
                            Iso = "TM",
                            Name = "Turkmenistán"
                        },
                        new
                        {
                            Id = 225,
                            Iso = "TR",
                            Name = "Turquía"
                        },
                        new
                        {
                            Id = 226,
                            Iso = "TV",
                            Name = "Tuvalu"
                        },
                        new
                        {
                            Id = 227,
                            Iso = "UA",
                            Name = "Ucrania"
                        },
                        new
                        {
                            Id = 228,
                            Iso = "UG",
                            Name = "Uganda"
                        },
                        new
                        {
                            Id = 229,
                            Iso = "UY",
                            Name = "Uruguay"
                        },
                        new
                        {
                            Id = 230,
                            Iso = "UZ",
                            Name = "Uzbekistán"
                        },
                        new
                        {
                            Id = 231,
                            Iso = "VU",
                            Name = "Vanuatu"
                        },
                        new
                        {
                            Id = 232,
                            Iso = "VE",
                            Name = "Venezuela"
                        },
                        new
                        {
                            Id = 233,
                            Iso = "VN",
                            Name = "Vietnam"
                        },
                        new
                        {
                            Id = 234,
                            Iso = "VG",
                            Name = "Islas Vírgenes Británicas"
                        },
                        new
                        {
                            Id = 235,
                            Iso = "VI",
                            Name = "Islas Vírgenes de los Estados Unidos"
                        },
                        new
                        {
                            Id = 236,
                            Iso = "WF",
                            Name = "Wallis y Futuna"
                        },
                        new
                        {
                            Id = 237,
                            Iso = "YE",
                            Name = "Yemen"
                        },
                        new
                        {
                            Id = 238,
                            Iso = "DJ",
                            Name = "Yibuti"
                        },
                        new
                        {
                            Id = 239,
                            Iso = "ZM",
                            Name = "Zambia"
                        },
                        new
                        {
                            Id = 240,
                            Iso = "ZW",
                            Name = "Zimbabue"
                        });
                });

            modelBuilder.Entity("SupplierDueDiligence.API.Domain.Models.ScreeningSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ScreeningSources");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "OFAC",
                            Name = "OFAC"
                        },
                        new
                        {
                            Id = 2,
                            Code = "WORLD_BANK",
                            Name = "World Bank"
                        },
                        new
                        {
                            Id = 3,
                            Code = "OFFSHORE_LEAKS",
                            Name = "Offshore Leaks"
                        });
                });

            modelBuilder.Entity("SupplierDueDiligence.API.Domain.Models.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("AnnualRevenue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommercialName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaxId")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("LastUpdated");

                    b.HasIndex("TaxId")
                        .IsUnique();

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Av. Reforma 123",
                            AnnualRevenue = 500000.00m,
                            BusinessName = "Tech Solutions SA",
                            CommercialName = "TechSol",
                            CountryId = 2,
                            Email = "contact@techsol.com",
                            LastUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "+525512345678",
                            TaxId = "12345678901",
                            Website = "https://techsol.com"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Calle Mayor 45",
                            AnnualRevenue = 750000.00m,
                            BusinessName = "Global Logistics",
                            CommercialName = "LogGlobal",
                            CountryId = 3,
                            Email = "info@logglobal.es",
                            LastUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "+34987654321",
                            TaxId = "98765432109",
                            Website = "https://logglobal.es"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Calle 50, Panama",
                            AnnualRevenue = 2000000.00m,
                            BusinessName = "Offshore Investments",
                            CommercialName = "Offshore Corp",
                            CountryId = 5,
                            Email = "admin@offshore.pa",
                            LastUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "+5076543210",
                            TaxId = "11122334455",
                            Website = "https://offshore.pa"
                        });
                });

            modelBuilder.Entity("SupplierDueDiligence.API.Domain.Models.Supplier", b =>
                {
                    b.HasOne("SupplierDueDiligence.API.Domain.Models.Country", "Country")
                        .WithMany("Suppliers")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("SupplierDueDiligence.API.Domain.Models.Country", b =>
                {
                    b.Navigation("Suppliers");
                });
#pragma warning restore 612, 618
        }
    }
}
